version: '3'
services:
  server:
    container_name: 'homework-server'
    build: './server'
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn run start
    ports:
      - 5050:5050
    stdin_open: true
    tty: true
  client:
    container_name: 'homework-client'
    build: './client'
    volumes:
      - ./client:/app
      - /app/node_modules
    command: yarn run start
    ports:
      - 8080:8080
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
