version: '3'
services:
  server:
    container_name: 'homework-server'
    build: './server'
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn run start
    ports:
      - 5050:5050
    links:
      - mongo
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  client:
    container_name: 'homework-client'
    build: './client'
    volumes:
      - ./client:/app
      - /app/node_modules
    command: yarn run start
    ports:
      - 8080:8080
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
  mongo:
    container_name: homework-mongo
    image: mongo:4.1
    ports:
      - 30001:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongo/data:/data/db
    command: mongod --logpath=/dev/null
    restart: always
